name: 'Terraform CD'

on:
  pull_request:
    branches:
      - master
         

jobs:
  test:
       runs-on: ubuntu-latest
       env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
       steps:
       - name: script
         run: |
          echo "$PR_AUTHOR is requesting access to mk.misbah_uddin@live.com"
         shell: bash
