name: 'Terraform CD'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
         

jobs:
  test:
       if: github.event.pull_request.merged == true
       runs-on: ubuntu-latest
       env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
       steps:
       - name: script
         run: |
          echo "$PR_AUTHOR is requesting merge to master"
         shell: bash
