name: 'Terraform CD'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
         

jobs:
  test:
       runs-on: ubuntu-latest
       env:
          PR_AUTHOR: ${{ github.event.push.user.login }}
       steps:
       - name: script
         uses: actions/checkout@v2
       - run: |
           echo "$PR_AUTHOR is requesting mergee to master"
         shell: bash
