name: 'Terraform CI'

on:
  pull_request:
    types: [closed]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
    - name: Get current time
      id: time
      run: echo "::set-output name=time::$(date +'%Y-%m-%dT%H:%M:%S')""
        
    - name: Set up gcloud Cloud SDK environment
      env:
       PROJECT_ID: ${{ secrets.PUBSUB_PROJECT }}
       GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PUBSUB_PROJECT }}
          export_default_credentials: true
          
    - run: |-
        gcloud pubsub topics publish notifications. --message "${{ github.event.pull_request.user.login }} requested access to GCE VM" --attribute="requestor=${{ github.event.pull_request.user.login }},email=${{ github.event.pull_request.user.login }}@sourcedgroup.com,date=${{ steps.date.outputs.date }},time=${{ steps.time.outputs.time }}"
