name: 'Terraform CD'

on:
  pull_request:
    branches:
      - master
         

jobs:
    setup:
         name: Setup, Build, Publish, and Deploy
         runs-on: ubuntu-latest
         
         defaults:
          run:
           shell: bash
           
         steps:
         - name: Print GitHub context
           uses: actions/checkout@v2
         - run: echo "$GITHUB_CONTEXT"
           env:
            GITHUB_CONTEXT: ${{ toJson(github.event.issue.user.login) }} 
