name: 'Terraform CI'

on:
  push:
    branches:
      - master
      - develop
      
jobs:
 setup-build-publish-deploy:
  name: Setup, Build, Publish, and Deploy
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set Name
      run: |
       - name: Discord Commits
        echo "AUTHOR_NAME=${ github.event.head_commit.author.name }"
        echo "AUTHOR_EMAIL=${ github.event.head_commit.author.email }"
       

      




  
       
