name: 'Terraform CI'

on:
  push:
    branches:
      - master
      - develop
      
jobs:
 setup-build-publish-deploy:
  name: Setup, Build, Publish, and Deploy
  runs-on: ubuntu-latest

  steps:
      - name: Discord Commits
        AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
        AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
       

      




  
       
