name: 'Terraform CI'

on: pull_request

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  setup-build-publish-deploy:
    name: get request name
    runs-on: ubuntu-latest
    steps:
      - name: view the PR number
        run: |
          echo "PR number = ${{ github.event.pull_request.number }}"
          echo "PR number = ${{ env.PR_NUMBER }}"

on:
  push:
    branches:
      - master
      - develop

env:
  PROJECT_ID: ${{ secrets.PUBSUB_PROJECT }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:
    
    - name: get names
      uses: google-github-actions/setup-gcloud@v0.2.0
    - run: yarn deploy --stage $(echo "${{ github.event.pull_request.number}}")
    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PUBSUB_PROJECT }}
          export_default_credentials: true
          
    - run: |-
        gcloud pubsub topics publish notifications. --message createdbymisbah
        gcloud pubsub subscriptions pull --auto-ack echo
