name: 'Terraform CI'

on:
  push:
    branches:
      - master
      - develop
  
env:
 GITHUB_CONTEXT: ${{ toJson(github) }}
      
jobs:
 setup-build-publish-deploy:
  name: Setup, Build, Publish, and Deploy
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set Name
      run: |
       - name: Discord
        echo "GITUB_CONTEXT: ${{ github.event.pull_request.user.login }}"

       

      




  
       
