name: 'Terraform CI'

on:
  push:
    branches:
      - master
      - develop
      
jobs:
 setup-build-publish-deploy:
  name: Setup, Build, Publish, and Deploy
  runs-on: ubuntu-latest

  steps:
     - name: View PR author
       run: echo "This PR is opened by ${{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}**.\nDiff: {{ github.context.payload.compare }}"
       

      




  
       
