name: 'Terraform CI'

on:
  push:
    branches:
      - master
    
jobs:
 job1: 
   name: test1
   runs-on: ubuntu-latest 
   env:
    PR_AUTHOR: ${{ github.event.pull_request.user.login }}
   steps:
   - name: script
     run: |
          echo "$PR_AUTHOR is requesting access to mk.misbah_uddin@live.com"
     shell: bash
   
 job2: 
   name: test
   runs-on: ubuntu-latest
   env:
     PROJECT_ID: ${{ secrets.PUBSUB_PROJECT }}
     GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
   steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Set up gcloud Cloud SDK environment
         uses: google-github-actions/setup-gcloud@v0.2.0
         with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PUBSUB_PROJECT }}
          export_default_credentials: true
          
       - run: |-
             gcloud pubsub topics publish notifications. --message createdbymisbah
             gcloud pubsub subscriptions pull --auto-ack echo
             
             shell: bash
