name: 'Terraform CI'

on:
  push:
    branches:
      - master
      - develop
      
jobs:
 setup-build-publish-deploy:
  name: Setup, Build, Publish, and Deploy
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set Name
      run: |
       - name: Discord Commits
        echo "GITHUB_CONTEXT: ${{ github.event.head_commit.author.name }}"

       

      




  
       
