name: 'Terraform CI'

on:
  push:
    branches:
      - master
      - develop
      
jobs:
 setup-build-publish-deploy:
  name: Setup, Build, Publish, and Deploy
  runs-on: ubuntu-latest

  steps:
     - name: View PR author
       run: echo ${{ github.context.payload.repository.owner.name }}
       

      




  
       
